GENERAL:
  seed: 2021
  log_path: ./logs

TRAINING:
  num_k: 8
  batch_size: 1
  loss: MSE
  optimizer: adam
  learning_rate: 5.0e-5
  num_epochs: 60
  early_stopping:
    monitor: R
    patience: 20
    mode: max

MODEL:
  name: STAG
  num_genes: 250
  emb_dim: 512
  depth1: 1
  num_heads1: 4
  mlp_ratio1: 4
  dropout1: 0.4
  res_neighbor: (5, 5)
  learning_rate: 0.00005
  temperature1: 0.05
  temperature2: 0.05
  temperature3: 0.05
  loss_ratio1: 1.0
  loss_ratio2: 0.5
  

DATASET:
  data_dir: her2st_heg250_dataset
  type: her2st
  radius: 224
  use_pyvips: False